# Generated by Django 4.1.7 on 2023-10-23 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShortTermCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course", models.CharField(max_length=255)),
                ("subtitle", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="course_images/")),
                (
                    "status",
                    models.CharField(
                        choices=[("Enable", "Enable"), ("Disable", "Disable")],
                        default="Enable",
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
