# Generated by Django 4.1.7 on 2023-10-23 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shorttermcourse",
            old_name="course",
            new_name="title",
        ),
    ]
