# Generated by Django 4.1.7 on 2023-10-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_shorttermcourse_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="shorttermcourse",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
